name: analysis
channels:
    - conda-forge
    - nodefaults
dependencies:
    - numpy
    - xarray
    - matplotlib
    - cartopy
    - dask
    - jupyter
    - jupyterlab
    - netCDF4
    - pop_tools
    - intake 
    - fsspec
    - cmocean
